### ISSUE TITLE
Is the Mongo collection name hardcoded?

### ISSUE THREAD

**Issue by kzayasru** [markpbaggett/digital_commons_data_dump_to_mongo#1]
Trying to create a new collection with `python3 add.py --path ../trace-metadata-xml --collection trace` results in a Mongo collection created under `dltndata`.

``` shell
vagrant@vagrant-ubuntu-trusty-64:~$ mongo
MongoDB shell version: 2.6.4
connecting to: test
> show dbs
admin     (empty)
dltn      (empty)
dltndata  0.203GB
local     0.078GB
trace     (empty)
```

Is the [problem here at line 13](https://github.com/markpbaggett/digital_commons_data_dump_to_mongo/blob/master/add.py#L13)?

Just realized that the `dltndata` is the database and add.py creates a collection under dltndata using the provided name.

**Comment by markpbaggett** [comment]
Good eye.  Yeah, dltndata is the database and the collection lives in that database. Unless there is a problem, I think the collection in your case is called trace. To be sure, you can login to mongo and type "use dltndata" then "show collections".  Exit with ctrl + d.
